---
sudo: required
language: ruby
cache: bundler
dist: trusty

services:
- docker

before_install:
- gem --version
- bundle version

matrix:
  include:
  # verify lint and unit
  - rvm: 2.3.1
    gemfile: Gemfile
    bundler_args: "--without integration guard tools"
  # integration tests
  - rvm: 2.3.1
    bundler_args: "--without guard tools"
    script: bundle exec rake test:integration OS='centos oracle'
    gemfile: Gemfile
  - rvm: 2.3.1
    bundler_args: "--without guard tools"
    script: bundle exec rake test:integration OS='ubuntu debian'
    gemfile: Gemfile
